# Generated by Django 5.0.7 on 2026-09-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='answer_by',
            field=models.CharField(choices=[('EVERYBODY', 'everybody'), ('LOGIN', 'login')], default='EVERYBODY', max_length=15),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='goal',
            field=models.CharField(default='HaHa', max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('FINISHED', 'finished'), ('IN_PROGRESS', 'in progress'), ('STOPPED', 'stopped')], default='DRAFT', max_length=15),
        ),
    ]
