# Generated by Django 5.0.7 on 2026-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_questionnaire_answer_by_questionnaire_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='has_alternatives',
            field=models.BooleanField(default=False),
        ),
    ]
