# Generated by Django 5.0.7 on 2026-09-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questionnaire_has_alternatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=models.JSONField(null=True),
        ),
    ]
