# Generated by Django 5.0.7 on 2026-09-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_answer_user_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
